### PR TITLE
Upgrade Newtonsoft Due to CVE in below 13.x versions

### PR DESCRIPTION
**Pull request by Christian-Oleson**

### CODE REVIEW

**Comment by aelmhorst** [comment]
This repo is a clone and is not maintained. Is the original repo no longer available?

**Comment by Christian-Oleson** [comment]
> This repo is a clone and is not maintained. Is the original repo no longer available?

What is the original repo then?

**Comment by aelmhorst** [comment]
I don't see the original repo public any more, so it may have been removed. It looks like there is another fork that is more active and ahead of this one: https://github.com/edgenuity/API-ClientLibrary-DotNet

**Comment by Christian-Oleson** [comment]
> I don't see the original repo public any more, so it may have been removed. It looks like there is another fork that is more active and ahead of this one: https://github.com/edgenuity/API-ClientLibrary-DotNet

Regardless, the security hole should still be fixed.

**Pull request closed without merging**
